version: '3.8'

services:
  web:
    build: ./server
    command: python -u server/main.py
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links: 
      - db

  db:
    image: mongo:latest
    hostname: mongohost
    ports:
      - 27017:27017